# Generated by Django 2.2 on 2020-08-18 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeaveMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], default=1)),
                ('title', models.CharField(max_length=50, verbose_name='留言主题')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('file', models.FileField(upload_to='media/message/files', verbose_name='留言文件')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户留言',
                'verbose_name_plural': '用户留言',
            },
        ),
    ]
