# Generated by Django 2.2 on 2020-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0002_userleavemsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavemsg',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/message/files', verbose_name='留言文件'),
        ),
        migrations.AlterField(
            model_name='userleavemsg',
            name='msg_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], default=1, verbose_name='留言类型'),
        ),
    ]
