# Generated by Django 2.2 on 2020-08-18 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_actions', '0004_auto_20200818_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavemsg',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_msg', to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
