# Generated by Django 2.2 on 2020-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0006_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='addr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='phone',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='receiveName',
            new_name='signer_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='area',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(default=1, max_length=20, verbose_name='地区'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=20, verbose_name='城市'),
        ),
    ]
