# Generated by Django 2.2 on 2020-08-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200811_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.GoodsCategorys', verbose_name='商品类别'),
        ),
    ]
