# Generated by Django 2.2 on 2020-08-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200812_0012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsCategorys',
            new_name='GoodCategories',
        ),
        migrations.RenameModel(
            old_name='GoodsImages',
            new_name='GoodImages',
        ),
    ]
