# Generated by Django 2.2 on 2020-08-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20200817_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodimages',
            old_name='images',
            new_name='image',
        ),
    ]
