# Generated by Django 2.2 on 2020-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_order_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_script',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='订单留言'),
        ),
    ]
